In [7]:
import pandas as pd
import os
from openpyxl import load_workbook
from IdMapping import clean_provider_ids

In [8]:
# Define the path to the Excel file
folder_path = "../BoS (Business Objects) Raw Data Reports - Deidentified"
file_name = "143 RAW Client Data Export v3_EE Workflow.xlsx"
file_path = os.path.join(folder_path, file_name)

In [9]:
# Get the program from the file name
program_name = file_name.split(" ")[0]
print(f"We are looking at Program {program_name} data")

We are looking at Program 143 data

In [10]:
df_disability_ent = pd.read_excel(file_path, sheet_name="DISABILITY ENT")
df_disability_ent.head()

,EE Provider ID,Disability Determination (Entry),Disability Type (Entry),"If Yes, Expected to be of long-continued and indefinite duration and substantially impairs ability to live independently(10678)",Disability Start Date (Entry),End Date(874),Provider (417-provider),Date Added (417-date_added)
0,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Alcohol Use Disorder (HUD),NaN,2015-08-28 12:00:00.779,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.230
1,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Both Alcohol and Drug Use Disorder (HUD),NaN,2015-08-28 12:00:00.784,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.426
2,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Developmental (HUD),NaN,2015-08-28 12:00:00.853,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.456
3,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Drug Use Disorder (HUD),NaN,2015-08-28 12:00:00.857,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.458
4,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),HIV/AIDS (HUD),NaN,2015-08-28 12:00:00.858,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.444

In [11]:
# Clean EE Provider ID
df_disability_ent = clean_provider_ids(df_disability_ent)
df_disability_ent.head()

,EE Provider ID,Disability Determination (Entry),Disability Type (Entry),"If Yes, Expected to be of long-continued and indefinite duration and substantially impairs ability to live independently(10678)",Disability Start Date (Entry),End Date(874),Provider (417-provider),Date Added (417-date_added),Provider Abbrev,Provider Tree
0,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Alcohol Use Disorder (HUD),NaN,2015-08-28 12:00:00.779,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.230,Grafton SHU,143
1,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Both Alcohol and Drug Use Disorder (HUD),NaN,2015-08-28 12:00:00.784,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.426,Grafton SHU,143
2,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Developmental (HUD),NaN,2015-08-28 12:00:00.853,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.456,Grafton SHU,143
3,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),Drug Use Disorder (HUD),NaN,2015-08-28 12:00:00.857,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.458,Grafton SHU,143
4,"Community Housing Network, Inc. - Grafton SHU ...",No (HUD),HIV/AIDS (HUD),NaN,2015-08-28 12:00:00.858,NaT,HARA - Oakland County - ESG Screening(8319),2015-08-28 09:15:36.444,Grafton SHU,143

In [18]:
# Count the number of 'Yes' and 'No' in the 'Disability Determination (Entry)' column
entry_counts = df_disability_ent.groupby(["Provider Abbrev", "Provider Tree"])['Disability Determination (Entry)'].value_counts(dropna=True).reset_index()
entry_counts

       Provider Abbrev Provider Tree Disability Determination (Entry)  count
0          Grafton SHU           143                         No (HUD)    248
1          Grafton SHU           143                        Yes (HUD)     17
2   Jefferson Oaks SHU           143                         No (HUD)    640
3   Jefferson Oaks SHU           143                        Yes (HUD)     55
4   Jefferson Oaks SHU           143        Client doesn't know (HUD)      7
5   Jefferson Oaks SHU           143         Data not collected (HUD)      2
6              OCHLAP1           143                         No (HUD)    200
7              OCHLAP1           143                        Yes (HUD)     80
8              OCHLAP2           143                         No (HUD)    171
9              OCHLAP2           143                        Yes (HUD)     48
10             OCHLAP5           143                         No (HUD)     62
11             OCHLAP5           143                        Yes (HUD)     14
12             OLAP CG           143                         No (HUD)    987
13             OLAP CG           143                        Yes (HUD)    176
14             OLAP CG           143        Client doesn't know (HUD)      1
15               OLAP2           143                         No (HUD)   1021
16               OLAP2           143                        Yes (HUD)    186
17               OLAP2           143        Client doesn't know (HUD)      1
18                ORRH           143                         No (HUD)    319
19                ORRH           143                        Yes (HUD)     17
20               ORRH2           143                         No (HUD)   1651
21               ORRH2           143                        Yes (HUD)    129
22   Palmer Pointe SHU           143                         No (HUD)    277
23   Palmer Pointe SHU           143                        Yes (HUD)     24
24   Palmer Pointe SHU           143        Client doesn't know (HUD)      2
25      Unity Park SHU           143                         No (HUD)    580
26      Unity Park SHU           143                        Yes (HUD)     83
27      Unity Park SHU           143        Client doesn't know (HUD)      2

In [19]:
entry_counts.columns = ['Provider Abbrev', 'Provider Tree', 'Disability Status', 'Count']
entry_counts['Assessment Stage'] = 'Entry'
entry_counts

,Provider Abbrev,Provider Tree,Disability Status,Count,Assessment Stage
0,Grafton SHU,143,No (HUD),248,Entry
1,Grafton SHU,143,Yes (HUD),17,Entry
2,Jefferson Oaks SHU,143,No (HUD),640,Entry
3,Jefferson Oaks SHU,143,Yes (HUD),55,Entry
4,Jefferson Oaks SHU,143,Client doesn't know (HUD),7,Entry
5,Jefferson Oaks SHU,143,Data not collected (HUD),2,Entry
6,OCHLAP1,143,No (HUD),200,Entry
7,OCHLAP1,143,Yes (HUD),80,Entry
8,OCHLAP2,143,No (HUD),171,Entry
9,OCHLAP2,143,Yes (HUD),48,Entry
10,OCHLAP5,143,No (HUD),62,Entry
11,OCHLAP5,143,Yes (HUD),14,Entry
12,OLAP CG,143,No (HUD),987,Entry
13,OLAP CG,143,Yes (HUD),176,Entry
14,OLAP CG,143,Client doesn't know (HUD),1,Entry
15,OLAP2,143,No (HUD),1021,Entry
16,OLAP2,143,Yes (HUD),186,Entry
17,OLAP2,143,Client doesn't know (HUD),1,Entry
18,ORRH,143,No (HUD),319,Entry
19,ORRH,143,Yes (HUD),17,Entry
20,ORRH2,143,No (HUD),1651,Entry
21,ORRH2,143,Yes (HUD),129,Entry
22,Palmer Pointe SHU,143,No (HUD),277,Entry
23,Palmer Pointe SHU,143,Yes (HUD),24,Entry
24,Palmer Pointe SHU,143,Client doesn't know (HUD),2,Entry
25,Unity Park SHU,143,No (HUD),580,Entry
26,Unity Park SHU,143,Yes (HUD),83,Entry
27,Unity Park SHU,143,Client doesn't know (HUD),2,Entry